#include "markt.hpp"
#include <cstdlib> // for std::rand
#include <ctime>   // for std::time
#include <cmath>   // for std::sqrt

// Helper function to generate price using random walk
float generatePrice(float start, float tendenz, float streuung, float dt) {
    float sqdt = std::sqrt(dt);
    float Y = 2 * static_cast<float>(std::rand()) / static_cast<float>(RAND_MAX) - 1.0f;
    return start * (1 + tendenz * dt + streuung * sqdt * Y);
}

Markt::Markt() {
    // Initialize with 10 funny named stocks with price generated by random walk
    std::vector<std::string> funnyNames = {
        "Sonnenblumenöl", "Klausurzulassungen", "Einhornstaub", "Schneckenrennen",
        "Glückskekse", "Pizzalieferungen", "Regenbogenfarben", "Katzenbilder",
        "Traumfänger", "Einhornglitzer"
    };

    std::srand(static_cast<unsigned int>(std::time(nullptr)));

    for (const auto& name : funnyNames) {
        float startPrice = 10.0f * (2 * static_cast<float>(std::rand()) / static_cast<float>(RAND_MAX) - 1.0f);
        float tendenz = 0.3f * (2 * static_cast<float>(std::rand()) / static_cast<float>(RAND_MAX) - 1.0f);
        float streuung = 0.8f;
        float dt = 0.001f;
        
        float price = generatePrice(startPrice, tendenz, streuung, dt);
        
        stocks.push_back(Ware(name, price, 0)); // Units initialized to 0
    }
}

std::vector<Ware> Markt::getStocks() const {
    return stocks;
}

void Markt::updatePrices() {
    for (auto& stock : stocks) {
        float startPrice = stock.getPrice();
        float tendenz = 0.3f * (2 * static_cast<float>(std::rand()) / static_cast<float>(RAND_MAX) - 1.0f);
        float streuung = 0.8f;
        float dt = 0.001f;
        
        float price = generatePrice(startPrice, tendenz, streuung, dt);
        
        stock.setPrice(price);
    }
}
